/**
 * Re-translates only the Portuguese entries that are still in English.
 * Run: npx tsx scripts/fix-pt-translations.ts
 */

import { readFileSync, writeFileSync } from 'fs'
import { articles } from '../src/data/articles'
import { articleTranslations } from '../src/data/article-translations'

function sleep(ms: number) {
  return new Promise(r => setTimeout(r, ms))
}

async function translateChunk(text: string, lang: string): Promise<string> {
  const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=${lang}&dt=t&q=${encodeURIComponent(text)}`
  try {
    const res = await fetch(url)
    const data = await res.json() as Array<Array<[string]>>
    const translated = data[0].map((x: [string]) => x[0]).join('')
    if (translated) return translated
  } catch { /* ignore */ }
  return text
}

async function translateText(text: string, lang: string): Promise<string> {
  if (!text || text.trim() === '') return text
  const MAX = 450
  if (text.length <= MAX) {
    await sleep(400)
    return translateChunk(text, lang)
  }
  const sentences = text.match(/[^.!?]+[.!?]+(\s|$)|[^.!?]+$/g) ?? [text]
  const chunks: string[] = []
  let current = ''
  for (const s of sentences) {
    if ((current + s).length > MAX) {
      if (current) chunks.push(current.trim())
      current = s
    } else {
      current += s
    }
  }
  if (current.trim()) chunks.push(current.trim())

  const parts: string[] = []
  for (const chunk of chunks) {
    await sleep(400)
    parts.push(await translateChunk(chunk, lang))
  }
  return parts.join(' ')
}

// Translates HTML body block-by-block (splitting on top-level tags) so
// each chunk passed to the translate API is plain text, not raw HTML.
async function translateHtmlBody(html: string, lang: string): Promise<string> {
  const blockRegex = /<(p|h1|h2|h3|blockquote|li)\b[^>]*>([\s\S]*?)<\/\1>/g
  let result = ''
  let lastIndex = 0
  let match: RegExpExecArray | null
  while ((match = blockRegex.exec(html))) {
    const [whole, tag, inner] = match
    result += html.slice(lastIndex, match.index)
    result += `<${tag}>${await translateText(inner, lang)}</${tag}>`
    lastIndex = match.index + whole.length
  }
  result += html.slice(lastIndex)
  return result
}

async function main() {
  // Deep-copy existing translations
  const result: typeof articleTranslations = JSON.parse(JSON.stringify(articleTranslations))

  for (const article of articles) {
    const existing = result[article.slug]?.['pt']
    // Re-translate if title is identical to English (= wasn't translated)
    const needsRetry = !existing || existing.title === article.title
    if (!needsRetry) {
      console.log(`✓ ${article.slug} PT already translated, skipping.`)
      continue
    }
    console.log(`\nTranslating "${article.slug}" → PT ...`)

    const title   = await translateText(article.title, 'pt')
    await sleep(300)
    const summary = await translateText(article.summary, 'pt')
    await sleep(300)
    const body = await translateHtmlBody(article.body, 'pt')
    console.log(`  ✓ done — "${title.slice(0, 60)}"`)

    if (!result[article.slug]) result[article.slug] = {}
    result[article.slug]['pt'] = { title, summary, body }
  }

  const ts = `// AUTO-GENERATED by scripts/translate-articles.ts — do not edit by hand.
// Re-run the script after adding new articles or locales.

export interface TranslatedArticle {
  title: string
  summary: string
  body: string
}

export const articleTranslations: Record<string, Partial<Record<string, TranslatedArticle>>> =
${JSON.stringify(result, null, 2)}
`
  writeFileSync('src/data/article-translations.ts', ts, 'utf8')
  console.log('\n✅  Wrote src/data/article-translations.ts')
}

main().catch(e => { console.error(e); process.exit(1) })
