/**
 * Fixes all untranslated or partially-translated entries using Google Translate.
 * Detects issues by comparing BOTH title AND first paragraph body text.
 * Run: npx tsx scripts/fix-all-translations.ts
 */

import { writeFileSync } from 'fs'
import { articles } from '../src/data/articles'
import { articleTranslations } from '../src/data/article-translations'
import type { ArticleBlock } from '../src/types'

const LOCALES = ['fa', 'ar', 'hy', 'pt'] as const

function sleep(ms: number) { return new Promise(r => setTimeout(r, ms)) }

async function translateChunk(text: string, lang: string): Promise<string> {
  const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=${lang}&dt=t&q=${encodeURIComponent(text)}`
  try {
    const res = await fetch(url)
    const data = await res.json() as Array<Array<[string]>>
    const out = data[0].map((x: [string]) => x[0]).join('')
    if (out) return out
  } catch { /* ignore */ }
  return text
}

async function translateText(text: string, lang: string): Promise<string> {
  if (!text?.trim()) return text
  const MAX = 1000 // Google Translate handles longer chunks
  if (text.length <= MAX) {
    await sleep(120)
    return translateChunk(text, lang)
  }
  // Split on sentence boundaries for very long paragraphs
  const sentences = text.match(/[^.!?]+[.!?]+(\s|$)|[^.!?]+$/g) ?? [text]
  const chunks: string[] = []
  let cur = ''
  for (const s of sentences) {
    if ((cur + s).length > MAX) { if (cur) chunks.push(cur.trim()); cur = s }
    else cur += s
  }
  if (cur.trim()) chunks.push(cur.trim())

  const parts: string[] = []
  for (const chunk of chunks) {
    await sleep(120)
    parts.push(await translateChunk(chunk, lang))
  }
  return parts.join(' ')
}

async function translateBlock(block: ArticleBlock, lang: string): Promise<ArticleBlock> {
  if (block.type === 'paragraph' || block.type === 'subheading' || block.type === 'closing') {
    return { ...block, text: await translateText(block.text, lang) }
  }
  if (block.type === 'scripture-list') {
    const items = []
    for (const item of block.items) {
      items.push({ text: await translateText(item.text, lang), ref: item.ref })
    }
    return { type: 'scripture-list', items }
  }
  return block
}

function isTranslated(slug: string, locale: string, article: typeof articles[0]): boolean {
  const tx = articleTranslations[slug]?.[locale]
  if (!tx) return false
  // Title still English?
  if (tx.title === article.title) return false
  // First paragraph body still English?
  const firstPara = tx.body.find(b => b.type === 'paragraph') as { type: 'paragraph'; text: string } | undefined
  const engPara   = article.body.find(b => b.type === 'paragraph') as { type: 'paragraph'; text: string } | undefined
  if (firstPara && engPara && firstPara.text === engPara.text) return false
  return true
}

async function main() {
  const result: typeof articleTranslations = JSON.parse(JSON.stringify(articleTranslations))

  for (const article of articles) {
    if (!result[article.slug]) result[article.slug] = {}

    for (const locale of LOCALES) {
      if (isTranslated(article.slug, locale, article)) {
        console.log(`✓  ${article.slug} [${locale}] — OK, skipping`)
        continue
      }

      console.log(`\n→  Translating "${article.slug}" [${locale}] ...`)
      const title   = await translateText(article.title,   locale)
      await sleep(150)
      const summary = await translateText(article.summary, locale)

      const body: ArticleBlock[] = []
      for (let i = 0; i < article.body.length; i++) {
        process.stdout.write(`   block ${i+1}/${article.body.length}\r`)
        body.push(await translateBlock(article.body[i], locale))
      }
      console.log(`   ✓ done — "${title.slice(0, 60)}"`)
      result[article.slug][locale] = { title, summary, body }
    }
  }

  const ts = `// AUTO-GENERATED by scripts/translate-articles.ts — do not edit by hand.
// Re-run the script after adding new articles or locales.
import type { ArticleBlock } from '@/types'

export interface TranslatedArticle {
  title: string
  summary: string
  body: ArticleBlock[]
}

export const articleTranslations: Record<string, Partial<Record<string, TranslatedArticle>>> =
${JSON.stringify(result, null, 2)}
`
  writeFileSync('src/data/article-translations.ts', ts, 'utf8')
  console.log('\n✅  Wrote src/data/article-translations.ts')
}

main().catch(e => { console.error(e); process.exit(1) })
