/**
 * Fixes all untranslated or partially-translated entries using Google Translate.
 * Detects issues by comparing BOTH title AND first paragraph body text.
 * Run: npx tsx scripts/fix-all-translations.ts
 */

import { writeFileSync } from 'fs'
import { articles } from '../src/data/articles'
import { articleTranslations } from '../src/data/article-translations'

const LOCALES = ['fa', 'ar', 'hy', 'pt'] as const

function sleep(ms: number) { return new Promise(r => setTimeout(r, ms)) }

async function translateChunk(text: string, lang: string): Promise<string> {
  const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=${lang}&dt=t&q=${encodeURIComponent(text)}`
  try {
    const res = await fetch(url)
    const data = await res.json() as Array<Array<[string]>>
    const out = data[0].map((x: [string]) => x[0]).join('')
    if (out) return out
  } catch { /* ignore */ }
  return text
}

async function translateText(text: string, lang: string): Promise<string> {
  if (!text?.trim()) return text
  const MAX = 1000 // Google Translate handles longer chunks
  if (text.length <= MAX) {
    await sleep(120)
    return translateChunk(text, lang)
  }
  // Split on sentence boundaries for very long paragraphs
  const sentences = text.match(/[^.!?]+[.!?]+(\s|$)|[^.!?]+$/g) ?? [text]
  const chunks: string[] = []
  let cur = ''
  for (const s of sentences) {
    if ((cur + s).length > MAX) { if (cur) chunks.push(cur.trim()); cur = s }
    else cur += s
  }
  if (cur.trim()) chunks.push(cur.trim())

  const parts: string[] = []
  for (const chunk of chunks) {
    await sleep(120)
    parts.push(await translateChunk(chunk, lang))
  }
  return parts.join(' ')
}

// Translates HTML body block-by-block (splitting on top-level tags) so
// each chunk passed to the translate API is plain text, not raw HTML.
async function translateHtmlBody(html: string, lang: string): Promise<string> {
  const blockRegex = /<(p|h1|h2|h3|blockquote|li)\b[^>]*>([\s\S]*?)<\/\1>/g
  let result = ''
  let lastIndex = 0
  let match: RegExpExecArray | null
  while ((match = blockRegex.exec(html))) {
    const [whole, tag, inner] = match
    result += html.slice(lastIndex, match.index)
    result += `<${tag}>${await translateText(inner, lang)}</${tag}>`
    lastIndex = match.index + whole.length
  }
  result += html.slice(lastIndex)
  return result
}

function isTranslated(slug: string, locale: string, article: typeof articles[0]): boolean {
  const tx = articleTranslations[slug]?.[locale]
  if (!tx) return false
  if (tx.title === article.title) return false
  if (tx.body === article.body) return false
  return true
}

async function main() {
  const result: typeof articleTranslations = JSON.parse(JSON.stringify(articleTranslations))

  for (const article of articles) {
    if (!result[article.slug]) result[article.slug] = {}

    for (const locale of LOCALES) {
      if (isTranslated(article.slug, locale, article)) {
        console.log(`✓  ${article.slug} [${locale}] — OK, skipping`)
        continue
      }

      console.log(`\n→  Translating "${article.slug}" [${locale}] ...`)
      const title   = await translateText(article.title,   locale)
      await sleep(150)
      const summary = await translateText(article.summary, locale)
      await sleep(150)
      const body = await translateHtmlBody(article.body, locale)
      console.log(`   ✓ done — "${title.slice(0, 60)}"`)
      result[article.slug][locale] = { title, summary, body }
    }
  }

  const ts = `// AUTO-GENERATED by scripts/translate-articles.ts — do not edit by hand.
// Re-run the script after adding new articles or locales.

export interface TranslatedArticle {
  title: string
  summary: string
  body: string
}

export const articleTranslations: Record<string, Partial<Record<string, TranslatedArticle>>> =
${JSON.stringify(result, null, 2)}
`
  writeFileSync('src/data/article-translations.ts', ts, 'utf8')
  console.log('\n✅  Wrote src/data/article-translations.ts')
}

main().catch(e => { console.error(e); process.exit(1) })
