/**
 * Translates all articles into FA, AR, HY, PT using the free MyMemory API.
 * Outputs: src/data/article-translations.ts
 * Run: npx tsx scripts/translate-articles.ts
 */

import { writeFileSync } from 'fs'
import { articles } from '../src/data/articles'

const LOCALES = ['fa', 'ar', 'hy', 'pt'] as const
type Locale = typeof LOCALES[number]

const MYMEMORY_LANG: Record<Locale, string> = {
  fa: 'fa',
  ar: 'ar',
  hy: 'hy',
  pt: 'pt',
}

async function translateChunk(text: string, lang: string): Promise<string> {
  const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl=${lang}&dt=t&q=${encodeURIComponent(text)}`
  try {
    const res = await fetch(url)
    const data = await res.json() as Array<Array<[string]>>
    const translated = data[0].map((x: [string]) => x[0]).join('')
    if (translated) return translated
  } catch { /* ignore */ }
  return text
}

async function translateText(text: string, lang: string): Promise<string> {
  if (!text || text.trim() === '') return text
  // MyMemory free tier: 500 char limit per request
  const MAX = 480
  if (text.length <= MAX) {
    await sleep(250)
    return translateChunk(text, lang)
  }
  // Split on sentence boundaries
  const sentences = text.match(/[^.!?]+[.!?]+(\s|$)|[^.!?]+$/g) ?? [text]
  const chunks: string[] = []
  let current = ''
  for (const s of sentences) {
    if ((current + s).length > MAX) {
      if (current) chunks.push(current.trim())
      current = s
    } else {
      current += s
    }
  }
  if (current.trim()) chunks.push(current.trim())

  const parts: string[] = []
  for (const chunk of chunks) {
    await sleep(300)
    parts.push(await translateChunk(chunk, lang))
  }
  return parts.join(' ')
}

function sleep(ms: number) {
  return new Promise(r => setTimeout(r, ms))
}

// Translates HTML body block-by-block (splitting on top-level tags) so
// each chunk passed to the translate API is plain text, not raw HTML.
async function translateHtmlBody(html: string, lang: string): Promise<string> {
  const blockRegex = /<(p|h1|h2|h3|blockquote|li)\b[^>]*>([\s\S]*?)<\/\1>/g
  let result = ''
  let lastIndex = 0
  let match: RegExpExecArray | null
  while ((match = blockRegex.exec(html))) {
    const [whole, tag, inner] = match
    result += html.slice(lastIndex, match.index)
    result += `<${tag}>${await translateText(inner, lang)}</${tag}>`
    lastIndex = match.index + whole.length
  }
  result += html.slice(lastIndex)
  return result
}

interface TranslatedArticle {
  title: string
  summary: string
  body: string
}

async function main() {
  const result: Record<string, Record<string, TranslatedArticle>> = {}
  const total = articles.length * LOCALES.length
  let done = 0

  for (const article of articles) {
    result[article.slug] = {}
    for (const locale of LOCALES) {
      const lang = MYMEMORY_LANG[locale]
      console.log(`\n[${++done}/${total}] Translating "${article.slug}" → ${locale.toUpperCase()}`)

      const title = await translateText(article.title, lang)
      await sleep(200)
      const summary = await translateText(article.summary, lang)
      await sleep(200)
      const body = await translateHtmlBody(article.body, lang)
      console.log(`  ✓ done`)

      result[article.slug][locale] = { title, summary, body }
    }
  }

  // Serialise to TypeScript
  const ts = `// AUTO-GENERATED by scripts/translate-articles.ts — do not edit by hand.
// Re-run the script after adding new articles or locales.

export interface TranslatedArticle {
  title: string
  summary: string
  body: string
}

export const articleTranslations: Record<string, Partial<Record<string, TranslatedArticle>>> =
${JSON.stringify(result, null, 2)}
`
  writeFileSync('src/data/article-translations.ts', ts, 'utf8')
  console.log('\n✅  Wrote src/data/article-translations.ts')
}

main().catch(e => { console.error(e); process.exit(1) })
